- .gitignore
- .jscsrc
- LICENSE
- README.md
- app/index.js
- app/templates/.gitignore
- app/templates/.jscsrc
- app/templates/CONTRIBUTING.md
- app/templates/LICENSE
- app/templates/README.md
- app/templates/package.json
- app/templates/test/index.test.js
- app/templates/wercker.yml
- package.json
- test/app.js
- wercker.yml
This Yeoman generator creates a new npm module pre-loaded with:
- License
- Readme with a variety of badges
- Contributing doc
- JSCS config
- Wercker config with CD support
- Author default setup as you
> First pass at a Yeoman Generator

- package.json
https://docs.npmjs.com/files/package.json#files
> Fix files array so the package actually has some contents

- app/templates/package.json
> Changed dao's email

- app/templates/package.json
- package.json
Everyone is doing it these days
> Using my gmail account

- app/index.js
- app/templates/README.md
> The README should be linking to the Git Repo not the NPM Module name

- README.md
- app/index.js
- app/templates/test/index.test.js
- test/app.js
Updating Screwdriver links with our new pipelineIds from our API changes
> Updating SD links

- .npmignore
- README.md
- app/index.js
- app/templates/npmignore
- app/templates/package.json
- test/app.js
Related to https://github.com/screwdriver-cd/screwdriver/issues/324
> Adding .npmignore, changing bug location to SD, and removing Noah from new modules

- app/templates/CONTRIBUTING.md
- app/templates/package.json
- app/templates/screwdriver.yaml
- package.json
- screwdriver.yaml
Add commit message format to CONTRIBUTING.md. 
Relates to: https://github.com/screwdriver-cd/screwdriver/issues/373
> feat: add publish job in template & use semantic-release to publish	

- app/templates/package.json
- package.json
* Remove Noah
* Add Min, Reetika, and Jerry
> Updates to team members

- app/templates/package.json
New major version of jenkins-mocha.
> chore: Update jenkins-mocha

- app/templates/package.json
> Fix: Update contributors in package.json

- README.md
Try to fix pipeline by using proper semantic release syntax
> fix: Fix pipeline

- README.md
> fix: Remove typo from README

- app/templates/package.json
- package.json
> fix: update contributor email

- app/templates/package.json
- package.json
Add new team members to package.json
> fix: Add Jithin and Joel to package.json

- CONTRIBUTING.md
- app/templates/CONTRIBUTING.md
Similar to https://github.com/screwdriver-cd/screwdriver/pull/658#pullrequestreview-51364568
> fix: Fix typo in url

- app/index.js
- app/templates/package.json
- package.json
- screwdriver.yaml
Updating yeoman packages for Snyk vulnerabilities. Also updating contributors list.
> fix: Update yeoman packages

- CONTRIBUTING.md
- app/templates/CONTRIBUTING.md
- app/templates/LICENSE
- app/templates/package.json
- Add Cynthia, Tian, Filbert, Brian, Pranav
- Update license year
- Update contributing link
> fix: Update contributing and package.json

- app/templates/package.json
Update package versions and authors
> fix: Update jenkins-mocha version

- app/templates/LICENSE
- app/templates/package.json
- package.json
Also update yeoman-generator package version and license year
https://github.com/yeoman/generator/releases/tag/v3.0.0
> fix: Update dependencies for security

- .gitignore
- app/index.js
- app/templates/package.json
- app/templates/test/index.test.js
- package.json
- test/app.js
Add Alan to package.json file
Also update some npm packages.
> fix: Add Alan to package.json

- app/templates/package.json
- package.json
> fix: Add new members to template

- .gitignore
- README.md
- app/index.js
- app/templates/README.md
- test/app.js
https://github.com/screwdriver-cd/screwdriver/issues/2285
> fix: remove daviddm link [skip ci]

- mocha.config.json
- package.json
- screwdriver.yaml
- test/app.js
Sonarqube setting was broken and doesn't have test execution setting
Fix sonarqube setting
https://github.com/screwdriver-cd/screwdriver/issues/2288
> fix(2288): fix sonarqube setting

- app/index.js
- app/templates/gitignore
- app/templates/package.json
- app/templates/screwdriver.yaml
- package.json
This PR updates eslint-config-screwdriver package to v5.
Related to https://github.com/screwdriver-cd/screwdriver/issues/2492
> feat(2492): Update to eslint-config-screwdriver v5

- README.md
- app/templates/mocha.config.json
Running into issues trying with mocha when this file is missing.
N/A
> fix: Add mocha.config.json

- app/templates/package.json
> fix: update template
